### ISSUE TITLE
allows attempting allocs greater than isize::MAX

### ISSUE THREAD

**Issue by workingjubilee** [jyn514/Von-Neumann#1]
even if these requests are answered by underlying APIs, the resulting allocation is illegal in Rust, despite being plausible to allocate on e.g. 32-bit Windows.

gonna have to report you to RUSTSEC. :pensive:

h/t @wafflelapkin on [im-in.space](https://im-in.space/@wffl/111829937565589426).

**Comment by WaffleLapkin** [comment]
Thanks for opening this very important issue, glad to see my concern being seen. I propose to label this as `P-high` since this is a very (I don't want to continue writing this message, sorry)

**Comment by jyn514** [comment]
when you say "illegal in rust" do you mean specifically for the Allocator API or for any slice?

**Comment by jyn514** [comment]
> The first problem is that we index into arrays with unsigned integers, but GEP (and as a consequence ptr::offset) takes a signed integer. This means that half of the seemingly valid indices into an array will overflow GEP and actually go in the wrong direction! As such we must limit all allocations to isize::MAX elements. This actually means we only need to worry about byte-sized objects, because e.g. > isize::MAX u16s will truly exhaust all of the system's memory. However in order to avoid subtle corner cases where someone reinterprets some array of < isize::MAX objects as bytes, std limits all allocations to isize::MAX bytes.

what on earth

**Comment by workingjubilee** [comment]
it is illegal to have an allocation of any size greater than isize::MAX, yes, this applies to essentially every possible thing you can imagine.

**Comment by jyn514** [comment]
i am going to meow at this problem instead of fixing it :D


![](https://th-thumbnailer.cdn-si-edu.com/bgmkh2ypz03IkiRR50I-UMaqUQc=/1000x750/filters:no_upscale():focal(1061x707:1062x708)/https://tf-cmsv2-smithsonianmag-media.s3.amazonaws.com/filer_public/55/95/55958815-3a8a-4032-ac7a-ff8c8ec8898a/gettyimages-1067956982.jpg)

**Comment by jyn514** [comment]
ok i meowed at the problem AND fixed it https://github.com/jyn514/Von-Neumann/commit/626b446da243008c12e9fbe21c012b08a488c83c
